/*
* generated by Xtext
*/
package uk.ac.open.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RbacDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RbacElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rbac");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPolicyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPolicyPolicyParserRuleCall_0_0 = (RuleCall)cPolicyAssignment_0.eContents().get(0);
		private final Assignment cScenariosAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cScenariosScenariosParserRuleCall_1_0 = (RuleCall)cScenariosAssignment_1.eContents().get(0);
		
		//Rbac:
		//	policy=Policy scenarios=Scenarios;
		public ParserRule getRule() { return rule; }

		//policy=Policy scenarios=Scenarios
		public Group getGroup() { return cGroup; }

		//policy=Policy
		public Assignment getPolicyAssignment_0() { return cPolicyAssignment_0; }

		//Policy
		public RuleCall getPolicyPolicyParserRuleCall_0_0() { return cPolicyPolicyParserRuleCall_0_0; }

		//scenarios=Scenarios
		public Assignment getScenariosAssignment_1() { return cScenariosAssignment_1; }

		//Scenarios
		public RuleCall getScenariosScenariosParserRuleCall_1_0() { return cScenariosScenariosParserRuleCall_1_0; }
	}

	public class PolicyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Policy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPolicyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUsersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUsersUserParserRuleCall_2_0 = (RuleCall)cUsersAssignment_2.eContents().get(0);
		private final Assignment cRolesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRolesRoleParserRuleCall_3_0 = (RuleCall)cRolesAssignment_3.eContents().get(0);
		private final Assignment cPermissionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPermissionsPermissionParserRuleCall_4_0 = (RuleCall)cPermissionsAssignment_4.eContents().get(0);
		private final Assignment cResourcesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cResourcesResourceParserRuleCall_5_0 = (RuleCall)cResourcesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Policy:
		//	"policy" "{" users+=User* roles+=Role* permissions+=Permission* resources+=Resource* "}";
		public ParserRule getRule() { return rule; }

		//"policy" "{" users+=User* roles+=Role* permissions+=Permission* resources+=Resource* "}"
		public Group getGroup() { return cGroup; }

		//"policy"
		public Keyword getPolicyKeyword_0() { return cPolicyKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//users+=User*
		public Assignment getUsersAssignment_2() { return cUsersAssignment_2; }

		//User
		public RuleCall getUsersUserParserRuleCall_2_0() { return cUsersUserParserRuleCall_2_0; }

		//roles+=Role*
		public Assignment getRolesAssignment_3() { return cRolesAssignment_3; }

		//Role
		public RuleCall getRolesRoleParserRuleCall_3_0() { return cRolesRoleParserRuleCall_3_0; }

		//permissions+=Permission*
		public Assignment getPermissionsAssignment_4() { return cPermissionsAssignment_4; }

		//Permission
		public RuleCall getPermissionsPermissionParserRuleCall_4_0() { return cPermissionsPermissionParserRuleCall_4_0; }

		//resources+=Resource*
		public Assignment getResourcesAssignment_5() { return cResourcesAssignment_5; }

		//Resource
		public RuleCall getResourcesResourceParserRuleCall_5_0() { return cResourcesResourceParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ScenariosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Scenarios");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScenariosKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUserScenariosAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUserScenariosUserScenarioParserRuleCall_2_0 = (RuleCall)cUserScenariosAssignment_2.eContents().get(0);
		private final Assignment cUserRoleScenariosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUserRoleScenariosUserRoleScenarioParserRuleCall_3_0 = (RuleCall)cUserRoleScenariosAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Scenarios:
		//	"scenarios" "{" userScenarios+=UserScenario* userRoleScenarios+=UserRoleScenario* "}";
		public ParserRule getRule() { return rule; }

		//"scenarios" "{" userScenarios+=UserScenario* userRoleScenarios+=UserRoleScenario* "}"
		public Group getGroup() { return cGroup; }

		//"scenarios"
		public Keyword getScenariosKeyword_0() { return cScenariosKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//userScenarios+=UserScenario*
		public Assignment getUserScenariosAssignment_2() { return cUserScenariosAssignment_2; }

		//UserScenario
		public RuleCall getUserScenariosUserScenarioParserRuleCall_2_0() { return cUserScenariosUserScenarioParserRuleCall_2_0; }

		//userRoleScenarios+=UserRoleScenario*
		public Assignment getUserRoleScenariosAssignment_3() { return cUserRoleScenariosAssignment_3; }

		//UserRoleScenario
		public RuleCall getUserRoleScenariosUserRoleScenarioParserRuleCall_3_0() { return cUserRoleScenariosUserRoleScenarioParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRoleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRolesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cRolesRoleCrossReference_3_1_0 = (CrossReference)cRolesAssignment_3_1.eContents().get(0);
		private final RuleCall cRolesRoleIDTerminalRuleCall_3_1_0_1 = (RuleCall)cRolesRoleCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//User:
		//	"user" name=ID "{" ("role:" roles+=[Role])* "}";
		public ParserRule getRule() { return rule; }

		//"user" name=ID "{" ("role:" roles+=[Role])* "}"
		public Group getGroup() { return cGroup; }

		//"user"
		public Keyword getUserKeyword_0() { return cUserKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("role:" roles+=[Role])*
		public Group getGroup_3() { return cGroup_3; }

		//"role:"
		public Keyword getRoleKeyword_3_0() { return cRoleKeyword_3_0; }

		//roles+=[Role]
		public Assignment getRolesAssignment_3_1() { return cRolesAssignment_3_1; }

		//[Role]
		public CrossReference getRolesRoleCrossReference_3_1_0() { return cRolesRoleCrossReference_3_1_0; }

		//ID
		public RuleCall getRolesRoleIDTerminalRuleCall_3_1_0_1() { return cRolesRoleIDTerminalRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParentAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cParentRoleCrossReference_2_1_0 = (CrossReference)cParentAssignment_2_1.eContents().get(0);
		private final RuleCall cParentRoleIDTerminalRuleCall_2_1_0_1 = (RuleCall)cParentRoleCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSsodKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSsodAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSsodRoleCrossReference_4_1_0 = (CrossReference)cSsodAssignment_4_1.eContents().get(0);
		private final RuleCall cSsodRoleIDTerminalRuleCall_4_1_0_1 = (RuleCall)cSsodRoleCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDsodKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDsodAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cDsodRoleCrossReference_5_1_0 = (CrossReference)cDsodAssignment_5_1.eContents().get(0);
		private final RuleCall cDsodRoleIDTerminalRuleCall_5_1_0_1 = (RuleCall)cDsodRoleCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPermissionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPermissionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cPermissionsPermissionCrossReference_6_1_0 = (CrossReference)cPermissionsAssignment_6_1.eContents().get(0);
		private final RuleCall cPermissionsPermissionIDTerminalRuleCall_6_1_0_1 = (RuleCall)cPermissionsPermissionCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Role:
		//	"role" name=ID ("extends" parent=[Role])? "{" ("ssod:" ssod+=[Role])* ("dsod:" dsod+=[Role])* ("permission:"
		//	permissions+=[Permission])* "}";
		public ParserRule getRule() { return rule; }

		//"role" name=ID ("extends" parent=[Role])? "{" ("ssod:" ssod+=[Role])* ("dsod:" dsod+=[Role])* ("permission:"
		//permissions+=[Permission])* "}"
		public Group getGroup() { return cGroup; }

		//"role"
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" parent=[Role])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//parent=[Role]
		public Assignment getParentAssignment_2_1() { return cParentAssignment_2_1; }

		//[Role]
		public CrossReference getParentRoleCrossReference_2_1_0() { return cParentRoleCrossReference_2_1_0; }

		//ID
		public RuleCall getParentRoleIDTerminalRuleCall_2_1_0_1() { return cParentRoleIDTerminalRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("ssod:" ssod+=[Role])*
		public Group getGroup_4() { return cGroup_4; }

		//"ssod:"
		public Keyword getSsodKeyword_4_0() { return cSsodKeyword_4_0; }

		//ssod+=[Role]
		public Assignment getSsodAssignment_4_1() { return cSsodAssignment_4_1; }

		//[Role]
		public CrossReference getSsodRoleCrossReference_4_1_0() { return cSsodRoleCrossReference_4_1_0; }

		//ID
		public RuleCall getSsodRoleIDTerminalRuleCall_4_1_0_1() { return cSsodRoleIDTerminalRuleCall_4_1_0_1; }

		//("dsod:" dsod+=[Role])*
		public Group getGroup_5() { return cGroup_5; }

		//"dsod:"
		public Keyword getDsodKeyword_5_0() { return cDsodKeyword_5_0; }

		//dsod+=[Role]
		public Assignment getDsodAssignment_5_1() { return cDsodAssignment_5_1; }

		//[Role]
		public CrossReference getDsodRoleCrossReference_5_1_0() { return cDsodRoleCrossReference_5_1_0; }

		//ID
		public RuleCall getDsodRoleIDTerminalRuleCall_5_1_0_1() { return cDsodRoleIDTerminalRuleCall_5_1_0_1; }

		//("permission:" permissions+=[Permission])*
		public Group getGroup_6() { return cGroup_6; }

		//"permission:"
		public Keyword getPermissionKeyword_6_0() { return cPermissionKeyword_6_0; }

		//permissions+=[Permission]
		public Assignment getPermissionsAssignment_6_1() { return cPermissionsAssignment_6_1; }

		//[Permission]
		public CrossReference getPermissionsPermissionCrossReference_6_1_0() { return cPermissionsPermissionCrossReference_6_1_0; }

		//ID
		public RuleCall getPermissionsPermissionIDTerminalRuleCall_6_1_0_1() { return cPermissionsPermissionIDTerminalRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class PermissionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Permission");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPermissionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Permission:
		//	"permission" name=ID;
		public ParserRule getRule() { return rule; }

		//"permission" name=ID
		public Group getGroup() { return cGroup; }

		//"permission"
		public Keyword getPermissionKeyword_0() { return cPermissionKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPermissionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPermissionsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cPermissionsPermissionCrossReference_3_1_0 = (CrossReference)cPermissionsAssignment_3_1.eContents().get(0);
		private final RuleCall cPermissionsPermissionIDTerminalRuleCall_3_1_0_1 = (RuleCall)cPermissionsPermissionCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Resource:
		//	"resource" name=ID "{" ("permission:" permissions+=[Permission])* "}";
		public ParserRule getRule() { return rule; }

		//"resource" name=ID "{" ("permission:" permissions+=[Permission])* "}"
		public Group getGroup() { return cGroup; }

		//"resource"
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("permission:" permissions+=[Permission])*
		public Group getGroup_3() { return cGroup_3; }

		//"permission:"
		public Keyword getPermissionKeyword_3_0() { return cPermissionKeyword_3_0; }

		//permissions+=[Permission]
		public Assignment getPermissionsAssignment_3_1() { return cPermissionsAssignment_3_1; }

		//[Permission]
		public CrossReference getPermissionsPermissionCrossReference_3_1_0() { return cPermissionsPermissionCrossReference_3_1_0; }

		//ID
		public RuleCall getPermissionsPermissionIDTerminalRuleCall_3_1_0_1() { return cPermissionsPermissionIDTerminalRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class UserScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UserScenario");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGrantedScenarioParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cForbiddenScenarioParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//UserScenario:
		//	GrantedScenario | ForbiddenScenario;
		public ParserRule getRule() { return rule; }

		//GrantedScenario | ForbiddenScenario
		public Alternatives getAlternatives() { return cAlternatives; }

		//GrantedScenario
		public RuleCall getGrantedScenarioParserRuleCall_0() { return cGrantedScenarioParserRuleCall_0; }

		//ForbiddenScenario
		public RuleCall getForbiddenScenarioParserRuleCall_1() { return cForbiddenScenarioParserRuleCall_1; }
	}

	public class GrantedScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GrantedScenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGrantedScenarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUserKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUserAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cUserUserCrossReference_4_0 = (CrossReference)cUserAssignment_4.eContents().get(0);
		private final RuleCall cUserUserIDTerminalRuleCall_4_0_1 = (RuleCall)cUserUserCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRoleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRolesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cRolesRoleCrossReference_5_1_0 = (CrossReference)cRolesAssignment_5_1.eContents().get(0);
		private final RuleCall cRolesRoleIDTerminalRuleCall_5_1_0_1 = (RuleCall)cRolesRoleCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cResourceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cResourcesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cResourcesResourceCrossReference_6_1_0 = (CrossReference)cResourcesAssignment_6_1.eContents().get(0);
		private final RuleCall cResourcesResourceIDTerminalRuleCall_6_1_0_1 = (RuleCall)cResourcesResourceCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//GrantedScenario:
		//	"grantedScenario" name=ID "{" "user:" user=[User] ("role:" roles+=[Role])* ("resource:" resources+=[Resource])+ "}";
		public ParserRule getRule() { return rule; }

		//"grantedScenario" name=ID "{" "user:" user=[User] ("role:" roles+=[Role])* ("resource:" resources+=[Resource])+ "}"
		public Group getGroup() { return cGroup; }

		//"grantedScenario"
		public Keyword getGrantedScenarioKeyword_0() { return cGrantedScenarioKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"user:"
		public Keyword getUserKeyword_3() { return cUserKeyword_3; }

		//user=[User]
		public Assignment getUserAssignment_4() { return cUserAssignment_4; }

		//[User]
		public CrossReference getUserUserCrossReference_4_0() { return cUserUserCrossReference_4_0; }

		//ID
		public RuleCall getUserUserIDTerminalRuleCall_4_0_1() { return cUserUserIDTerminalRuleCall_4_0_1; }

		//("role:" roles+=[Role])*
		public Group getGroup_5() { return cGroup_5; }

		//"role:"
		public Keyword getRoleKeyword_5_0() { return cRoleKeyword_5_0; }

		//roles+=[Role]
		public Assignment getRolesAssignment_5_1() { return cRolesAssignment_5_1; }

		//[Role]
		public CrossReference getRolesRoleCrossReference_5_1_0() { return cRolesRoleCrossReference_5_1_0; }

		//ID
		public RuleCall getRolesRoleIDTerminalRuleCall_5_1_0_1() { return cRolesRoleIDTerminalRuleCall_5_1_0_1; }

		//("resource:" resources+=[Resource])+
		public Group getGroup_6() { return cGroup_6; }

		//"resource:"
		public Keyword getResourceKeyword_6_0() { return cResourceKeyword_6_0; }

		//resources+=[Resource]
		public Assignment getResourcesAssignment_6_1() { return cResourcesAssignment_6_1; }

		//[Resource]
		public CrossReference getResourcesResourceCrossReference_6_1_0() { return cResourcesResourceCrossReference_6_1_0; }

		//ID
		public RuleCall getResourcesResourceIDTerminalRuleCall_6_1_0_1() { return cResourcesResourceIDTerminalRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ForbiddenScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ForbiddenScenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForbiddenScenarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUserKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUserAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cUserUserCrossReference_4_0 = (CrossReference)cUserAssignment_4.eContents().get(0);
		private final RuleCall cUserUserIDTerminalRuleCall_4_0_1 = (RuleCall)cUserUserCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRoleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRolesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cRolesRoleCrossReference_5_1_0 = (CrossReference)cRolesAssignment_5_1.eContents().get(0);
		private final RuleCall cRolesRoleIDTerminalRuleCall_5_1_0_1 = (RuleCall)cRolesRoleCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cResourceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cResourcesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cResourcesResourceCrossReference_6_1_0 = (CrossReference)cResourcesAssignment_6_1.eContents().get(0);
		private final RuleCall cResourcesResourceIDTerminalRuleCall_6_1_0_1 = (RuleCall)cResourcesResourceCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ForbiddenScenario:
		//	"forbiddenScenario" name=ID "{" "user:" user=[User] ("role:" roles+=[Role])* ("resource:" resources+=[Resource])+ "}";
		public ParserRule getRule() { return rule; }

		//"forbiddenScenario" name=ID "{" "user:" user=[User] ("role:" roles+=[Role])* ("resource:" resources+=[Resource])+ "}"
		public Group getGroup() { return cGroup; }

		//"forbiddenScenario"
		public Keyword getForbiddenScenarioKeyword_0() { return cForbiddenScenarioKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"user:"
		public Keyword getUserKeyword_3() { return cUserKeyword_3; }

		//user=[User]
		public Assignment getUserAssignment_4() { return cUserAssignment_4; }

		//[User]
		public CrossReference getUserUserCrossReference_4_0() { return cUserUserCrossReference_4_0; }

		//ID
		public RuleCall getUserUserIDTerminalRuleCall_4_0_1() { return cUserUserIDTerminalRuleCall_4_0_1; }

		//("role:" roles+=[Role])*
		public Group getGroup_5() { return cGroup_5; }

		//"role:"
		public Keyword getRoleKeyword_5_0() { return cRoleKeyword_5_0; }

		//roles+=[Role]
		public Assignment getRolesAssignment_5_1() { return cRolesAssignment_5_1; }

		//[Role]
		public CrossReference getRolesRoleCrossReference_5_1_0() { return cRolesRoleCrossReference_5_1_0; }

		//ID
		public RuleCall getRolesRoleIDTerminalRuleCall_5_1_0_1() { return cRolesRoleIDTerminalRuleCall_5_1_0_1; }

		//("resource:" resources+=[Resource])+
		public Group getGroup_6() { return cGroup_6; }

		//"resource:"
		public Keyword getResourceKeyword_6_0() { return cResourceKeyword_6_0; }

		//resources+=[Resource]
		public Assignment getResourcesAssignment_6_1() { return cResourcesAssignment_6_1; }

		//[Resource]
		public CrossReference getResourcesResourceCrossReference_6_1_0() { return cResourcesResourceCrossReference_6_1_0; }

		//ID
		public RuleCall getResourcesResourceIDTerminalRuleCall_6_1_0_1() { return cResourcesResourceIDTerminalRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class UserRoleScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UserRoleScenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserRoleScenarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRoleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRolesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cRolesRoleCrossReference_3_1_0 = (CrossReference)cRolesAssignment_3_1.eContents().get(0);
		private final RuleCall cRolesRoleIDTerminalRuleCall_3_1_0_1 = (RuleCall)cRolesRoleCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//UserRoleScenario:
		//	"userRoleScenario" name=ID "{" ("role:" roles+=[Role])+ "}";
		public ParserRule getRule() { return rule; }

		//"userRoleScenario" name=ID "{" ("role:" roles+=[Role])+ "}"
		public Group getGroup() { return cGroup; }

		//"userRoleScenario"
		public Keyword getUserRoleScenarioKeyword_0() { return cUserRoleScenarioKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("role:" roles+=[Role])+
		public Group getGroup_3() { return cGroup_3; }

		//"role:"
		public Keyword getRoleKeyword_3_0() { return cRoleKeyword_3_0; }

		//roles+=[Role]
		public Assignment getRolesAssignment_3_1() { return cRolesAssignment_3_1; }

		//[Role]
		public CrossReference getRolesRoleCrossReference_3_1_0() { return cRolesRoleCrossReference_3_1_0; }

		//ID
		public RuleCall getRolesRoleIDTerminalRuleCall_3_1_0_1() { return cRolesRoleIDTerminalRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private RbacElements pRbac;
	private PolicyElements pPolicy;
	private ScenariosElements pScenarios;
	private UserElements pUser;
	private RoleElements pRole;
	private PermissionElements pPermission;
	private ResourceElements pResource;
	private UserScenarioElements pUserScenario;
	private GrantedScenarioElements pGrantedScenario;
	private ForbiddenScenarioElements pForbiddenScenario;
	private UserRoleScenarioElements pUserRoleScenario;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public RbacDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uk.ac.open.RbacDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Rbac:
	//	policy=Policy scenarios=Scenarios;
	public RbacElements getRbacAccess() {
		return (pRbac != null) ? pRbac : (pRbac = new RbacElements());
	}
	
	public ParserRule getRbacRule() {
		return getRbacAccess().getRule();
	}

	//Policy:
	//	"policy" "{" users+=User* roles+=Role* permissions+=Permission* resources+=Resource* "}";
	public PolicyElements getPolicyAccess() {
		return (pPolicy != null) ? pPolicy : (pPolicy = new PolicyElements());
	}
	
	public ParserRule getPolicyRule() {
		return getPolicyAccess().getRule();
	}

	//Scenarios:
	//	"scenarios" "{" userScenarios+=UserScenario* userRoleScenarios+=UserRoleScenario* "}";
	public ScenariosElements getScenariosAccess() {
		return (pScenarios != null) ? pScenarios : (pScenarios = new ScenariosElements());
	}
	
	public ParserRule getScenariosRule() {
		return getScenariosAccess().getRule();
	}

	//User:
	//	"user" name=ID "{" ("role:" roles+=[Role])* "}";
	public UserElements getUserAccess() {
		return (pUser != null) ? pUser : (pUser = new UserElements());
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}

	//Role:
	//	"role" name=ID ("extends" parent=[Role])? "{" ("ssod:" ssod+=[Role])* ("dsod:" dsod+=[Role])* ("permission:"
	//	permissions+=[Permission])* "}";
	public RoleElements getRoleAccess() {
		return (pRole != null) ? pRole : (pRole = new RoleElements());
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}

	//Permission:
	//	"permission" name=ID;
	public PermissionElements getPermissionAccess() {
		return (pPermission != null) ? pPermission : (pPermission = new PermissionElements());
	}
	
	public ParserRule getPermissionRule() {
		return getPermissionAccess().getRule();
	}

	//Resource:
	//	"resource" name=ID "{" ("permission:" permissions+=[Permission])* "}";
	public ResourceElements getResourceAccess() {
		return (pResource != null) ? pResource : (pResource = new ResourceElements());
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}

	//UserScenario:
	//	GrantedScenario | ForbiddenScenario;
	public UserScenarioElements getUserScenarioAccess() {
		return (pUserScenario != null) ? pUserScenario : (pUserScenario = new UserScenarioElements());
	}
	
	public ParserRule getUserScenarioRule() {
		return getUserScenarioAccess().getRule();
	}

	//GrantedScenario:
	//	"grantedScenario" name=ID "{" "user:" user=[User] ("role:" roles+=[Role])* ("resource:" resources+=[Resource])+ "}";
	public GrantedScenarioElements getGrantedScenarioAccess() {
		return (pGrantedScenario != null) ? pGrantedScenario : (pGrantedScenario = new GrantedScenarioElements());
	}
	
	public ParserRule getGrantedScenarioRule() {
		return getGrantedScenarioAccess().getRule();
	}

	//ForbiddenScenario:
	//	"forbiddenScenario" name=ID "{" "user:" user=[User] ("role:" roles+=[Role])* ("resource:" resources+=[Resource])+ "}";
	public ForbiddenScenarioElements getForbiddenScenarioAccess() {
		return (pForbiddenScenario != null) ? pForbiddenScenario : (pForbiddenScenario = new ForbiddenScenarioElements());
	}
	
	public ParserRule getForbiddenScenarioRule() {
		return getForbiddenScenarioAccess().getRule();
	}

	//UserRoleScenario:
	//	"userRoleScenario" name=ID "{" ("role:" roles+=[Role])+ "}";
	public UserRoleScenarioElements getUserRoleScenarioAccess() {
		return (pUserRoleScenario != null) ? pUserRoleScenario : (pUserRoleScenario = new UserRoleScenarioElements());
	}
	
	public ParserRule getUserRoleScenarioRule() {
		return getUserRoleScenarioAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
