/*
 * generated by Xtext
 */
package uk.ac.open.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRbacDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(uk.ac.open.rbacDSL.RbacDSLPackage.eINSTANCE);
		return result;
	}
}
