/*
 * generated by Xtext
 */
package uk.ac.open.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uk.ac.open.ui.internal.RbacDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RbacDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RbacDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RbacDSLActivator.getInstance().getInjector(RbacDSLActivator.UK_AC_OPEN_RBACDSL);
	}
	
}
