/*
* generated by Xtext
*/
package uk.ac.open;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RbacDSLStandaloneSetup extends RbacDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new RbacDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

