/*
 * generated by Xtext
 */
package uk.ac.open;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RbacDSLRuntimeModule extends uk.ac.open.AbstractRbacDSLRuntimeModule {

}
