/*
 * generated by Xtext
 */
package uk.ac.open.ui.contentassist

import uk.ac.open.ui.contentassist.AbstractRbacDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RbacDSLProposalProvider extends AbstractRbacDSLProposalProvider {
}
