/*
* generated by Xtext
*/
package uk.ac.open.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import uk.ac.open.services.RbacDSLGrammarAccess;

public class RbacDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private RbacDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected uk.ac.open.ui.contentassist.antlr.internal.InternalRbacDSLParser createParser() {
		uk.ac.open.ui.contentassist.antlr.internal.InternalRbacDSLParser result = new uk.ac.open.ui.contentassist.antlr.internal.InternalRbacDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getUserScenarioAccess().getAlternatives(), "rule__UserScenario__Alternatives");
					put(grammarAccess.getRbacAccess().getGroup(), "rule__Rbac__Group__0");
					put(grammarAccess.getPolicyAccess().getGroup(), "rule__Policy__Group__0");
					put(grammarAccess.getScenariosAccess().getGroup(), "rule__Scenarios__Group__0");
					put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
					put(grammarAccess.getUserAccess().getGroup_3(), "rule__User__Group_3__0");
					put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
					put(grammarAccess.getRoleAccess().getGroup_2(), "rule__Role__Group_2__0");
					put(grammarAccess.getRoleAccess().getGroup_4(), "rule__Role__Group_4__0");
					put(grammarAccess.getRoleAccess().getGroup_5(), "rule__Role__Group_5__0");
					put(grammarAccess.getRoleAccess().getGroup_6(), "rule__Role__Group_6__0");
					put(grammarAccess.getPermissionAccess().getGroup(), "rule__Permission__Group__0");
					put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
					put(grammarAccess.getResourceAccess().getGroup_3(), "rule__Resource__Group_3__0");
					put(grammarAccess.getGrantedScenarioAccess().getGroup(), "rule__GrantedScenario__Group__0");
					put(grammarAccess.getGrantedScenarioAccess().getGroup_5(), "rule__GrantedScenario__Group_5__0");
					put(grammarAccess.getGrantedScenarioAccess().getGroup_6(), "rule__GrantedScenario__Group_6__0");
					put(grammarAccess.getForbiddenScenarioAccess().getGroup(), "rule__ForbiddenScenario__Group__0");
					put(grammarAccess.getForbiddenScenarioAccess().getGroup_5(), "rule__ForbiddenScenario__Group_5__0");
					put(grammarAccess.getForbiddenScenarioAccess().getGroup_6(), "rule__ForbiddenScenario__Group_6__0");
					put(grammarAccess.getUserRoleScenarioAccess().getGroup(), "rule__UserRoleScenario__Group__0");
					put(grammarAccess.getUserRoleScenarioAccess().getGroup_3(), "rule__UserRoleScenario__Group_3__0");
					put(grammarAccess.getResourceRoleScenarioAccess().getGroup(), "rule__ResourceRoleScenario__Group__0");
					put(grammarAccess.getResourceRoleScenarioAccess().getGroup_5(), "rule__ResourceRoleScenario__Group_5__0");
					put(grammarAccess.getResourceScenarioAccess().getGroup(), "rule__ResourceScenario__Group__0");
					put(grammarAccess.getResourceScenarioAccess().getGroup_3(), "rule__ResourceScenario__Group_3__0");
					put(grammarAccess.getRbacAccess().getPolicyAssignment_0(), "rule__Rbac__PolicyAssignment_0");
					put(grammarAccess.getRbacAccess().getScenariosAssignment_1(), "rule__Rbac__ScenariosAssignment_1");
					put(grammarAccess.getPolicyAccess().getUsersAssignment_2(), "rule__Policy__UsersAssignment_2");
					put(grammarAccess.getPolicyAccess().getRolesAssignment_3(), "rule__Policy__RolesAssignment_3");
					put(grammarAccess.getPolicyAccess().getPermissionsAssignment_4(), "rule__Policy__PermissionsAssignment_4");
					put(grammarAccess.getPolicyAccess().getResourcesAssignment_5(), "rule__Policy__ResourcesAssignment_5");
					put(grammarAccess.getScenariosAccess().getUserScenariosAssignment_2(), "rule__Scenarios__UserScenariosAssignment_2");
					put(grammarAccess.getScenariosAccess().getUserRoleScenariosAssignment_3(), "rule__Scenarios__UserRoleScenariosAssignment_3");
					put(grammarAccess.getScenariosAccess().getResourceRoleScenariosAssignment_4(), "rule__Scenarios__ResourceRoleScenariosAssignment_4");
					put(grammarAccess.getScenariosAccess().getRoleScenariosAssignment_5(), "rule__Scenarios__RoleScenariosAssignment_5");
					put(grammarAccess.getUserAccess().getNameAssignment_1(), "rule__User__NameAssignment_1");
					put(grammarAccess.getUserAccess().getRolesAssignment_3_1(), "rule__User__RolesAssignment_3_1");
					put(grammarAccess.getRoleAccess().getNameAssignment_1(), "rule__Role__NameAssignment_1");
					put(grammarAccess.getRoleAccess().getParentAssignment_2_1(), "rule__Role__ParentAssignment_2_1");
					put(grammarAccess.getRoleAccess().getSsodAssignment_4_1(), "rule__Role__SsodAssignment_4_1");
					put(grammarAccess.getRoleAccess().getDsodAssignment_5_1(), "rule__Role__DsodAssignment_5_1");
					put(grammarAccess.getRoleAccess().getPermissionsAssignment_6_1(), "rule__Role__PermissionsAssignment_6_1");
					put(grammarAccess.getPermissionAccess().getNameAssignment_1(), "rule__Permission__NameAssignment_1");
					put(grammarAccess.getResourceAccess().getNameAssignment_1(), "rule__Resource__NameAssignment_1");
					put(grammarAccess.getResourceAccess().getPermissionsAssignment_3_1(), "rule__Resource__PermissionsAssignment_3_1");
					put(grammarAccess.getGrantedScenarioAccess().getNameAssignment_1(), "rule__GrantedScenario__NameAssignment_1");
					put(grammarAccess.getGrantedScenarioAccess().getUserAssignment_4(), "rule__GrantedScenario__UserAssignment_4");
					put(grammarAccess.getGrantedScenarioAccess().getRolesAssignment_5_1(), "rule__GrantedScenario__RolesAssignment_5_1");
					put(grammarAccess.getGrantedScenarioAccess().getResourcesAssignment_6_1(), "rule__GrantedScenario__ResourcesAssignment_6_1");
					put(grammarAccess.getForbiddenScenarioAccess().getNameAssignment_1(), "rule__ForbiddenScenario__NameAssignment_1");
					put(grammarAccess.getForbiddenScenarioAccess().getUserAssignment_4(), "rule__ForbiddenScenario__UserAssignment_4");
					put(grammarAccess.getForbiddenScenarioAccess().getRolesAssignment_5_1(), "rule__ForbiddenScenario__RolesAssignment_5_1");
					put(grammarAccess.getForbiddenScenarioAccess().getResourcesAssignment_6_1(), "rule__ForbiddenScenario__ResourcesAssignment_6_1");
					put(grammarAccess.getUserRoleScenarioAccess().getNameAssignment_1(), "rule__UserRoleScenario__NameAssignment_1");
					put(grammarAccess.getUserRoleScenarioAccess().getRolesAssignment_3_1(), "rule__UserRoleScenario__RolesAssignment_3_1");
					put(grammarAccess.getResourceRoleScenarioAccess().getNameAssignment_1(), "rule__ResourceRoleScenario__NameAssignment_1");
					put(grammarAccess.getResourceRoleScenarioAccess().getRoleAssignment_4(), "rule__ResourceRoleScenario__RoleAssignment_4");
					put(grammarAccess.getResourceRoleScenarioAccess().getResourcesAssignment_5_1(), "rule__ResourceRoleScenario__ResourcesAssignment_5_1");
					put(grammarAccess.getResourceScenarioAccess().getNameAssignment_1(), "rule__ResourceScenario__NameAssignment_1");
					put(grammarAccess.getResourceScenarioAccess().getResourcesAssignment_3_1(), "rule__ResourceScenario__ResourcesAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			uk.ac.open.ui.contentassist.antlr.internal.InternalRbacDSLParser typedParser = (uk.ac.open.ui.contentassist.antlr.internal.InternalRbacDSLParser) parser;
			typedParser.entryRuleRbac();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RbacDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RbacDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
