/*
* generated by Xtext
*/
package uk.ac.open.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.open.services.RbacDSLGrammarAccess;

public class RbacDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RbacDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected uk.ac.open.parser.antlr.internal.InternalRbacDSLParser createParser(XtextTokenStream stream) {
		return new uk.ac.open.parser.antlr.internal.InternalRbacDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Rbac";
	}
	
	public RbacDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RbacDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
