/*
* generated by Xtext
*/
package uk.ac.open;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RbacDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return uk.ac.open.ui.internal.RbacDSLActivator.getInstance().getInjector("uk.ac.open.RbacDSL");
	}
	
}
