/*
 * generated by Xtext
 */
package uk.ac.open.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RbacDSLUiModule extends uk.ac.open.ui.AbstractRbacDSLUiModule {
	public RbacDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
